### ISSUE TITLE
Figma Design Proposals

### ISSUE THREAD

**Issue by adityakmrmishra** [adityakmrmishra/Geet#14] opened 2023-10-01 13:26 UTC
**Description**:

We're looking for Figma design proposals to enhance our project's UI/UX. If you have design ideas or mockups, please share them in Figma and link them here.

**How to Contribute**:

1. Create designs in Figma.
2. Share the Figma link in the comments of this issue.

**Guidelines**:

- Ensure proposed designs align with our project's goals and target audience.
- Keep the design clean and user-friendly.

**Expected Outcome**:

Accepted Figma designs will be considered for implementation, and contributors will receive recognition.

**Timeline**:

Ongoing – Feel free to contribute Figma designs at any time.

We appreciate your creativity in enhancing our UI/UX through Figma!

**Comment by parinitapatil** [comment] 2023-10-01 13:37
I want to contribute.

**Comment by nishantshukla2884** [comment] 2023-10-02 16:46
i am interested , please assign it to me @adityakmrmishra

**Comment by parinitapatil** [comment] 2023-10-02 16:54
how to submit design ?

**Comment by adityakmrmishra** [comment] 2023-10-02 17:03
> i am interested , please assign it to me @adityakmrmishra 

Pls. read the description of issue properly we are asking for a design before assigning it anybody.

**Comment by parinitapatil** [comment] 2023-10-03 05:43
![image](https://github.com/adityakmrmishra/Geet/assets/119065651/52ebcc4a-8f14-4f94-abdc-844b9c7b34ea)
There are still some things that we could tweak and improve.

**Comment by l-ashish-gupta-l** [comment] 2023-10-03 15:45
Hello @parinitapatil ,

Firstly, we want to express our appreciation for your superb Figma design proposals! We're thrilled with your work.

Regarding your design, we have some specific enhancements in mind to make it even better. We'd like to incorporate a music album slider on the homepage and improve the player card. We also noticed that the bottom white footer, while attractive, may not be in extensive use due to the card player.

We're excited to see these improvements come to life, and we're delighted to assign this task to you. To streamline the process, please create a new folder in the code specifically for your Figma design. Add your Figma design to this folder and send a pull request. Once we receive it, we'll promptly assign it to you.

Once again, thank you for your valuable contributions to our project. We look forward to the enhancements you'll bring!

**Comment by parinitapatil** [comment] 2023-10-03 15:52
As a newcomer, could you guide me on how to create a folder for design files?

**Comment by adityakmrmishra** [comment] 2023-10-03 16:14
> As a newcomer, could you guide me on how to create a folder for design files?

Download Figma Design: Get your Figma design files ready on your computer.

Make a folder with suitable name or with name design in geet folder.

Place in "Design" Folder: Move the Figma design file into the existing "Design" folder in your Git repository.

Commit Changes: commit this addition to your repository with a clear message.

Push :  push your changes and make a pr .

**Comment by parinitapatil** [comment] 2023-10-03 16:34
Thanks for helping me out

**Comment by parinitapatil** [comment] 2023-10-03 16:36
Do you want me change the color pallette 🎨

**Comment by l-ashish-gupta-l** [comment] 2023-10-03 16:44
Sure, that sounds like a great idea! Please check your Twitter messages; I've sent you the invite email. Looking forward to collaborating on the design process and enhancements.

**Comment by parinitapatil** [comment] 2023-10-04 03:03
since the issue is closed do you still want to work on it?

**Comment by l-ashish-gupta-l** [comment] 2023-10-04 03:13
Hello,

I want to inform you that we've assigned the task related to this issue to you. We believe your expertise will be valuable in resolving it. Therefore, we're closing this issue as it is now actively being worked on.

Please feel free to reach out if you have any questions or need further assistance while working on the task. We appreciate your willingness to contribute to the project, and we look forward to your successful completion of the assignment.

Provide you Figma PULL REQUEST and we will merge it .

**Comment by parinitapatil** [comment] 2023-10-04 09:27
![image](https://github.com/adityakmrmishra/Geet/assets/119065651/2c42cb96-6ef2-4daa-9466-fab4998be959)

**Comment by adityakmrmishra** [comment] 2023-10-04 09:47
LGTM 
@parinitapatil  Start working on it

**Closed** 2023-11-15 10:12 UTC
Labels: UI/UX, hacktoberfest-accepted, hacktoberfest
